"""add user role

Revision ID: 7e0d2993ac06
Revises: a4f1d2b3c6e7
Create Date: 2026-02-14 12:31:23.920837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e0d2993ac06'
down_revision: Union[str, Sequence[str], None] = 'a4f1d2b3c6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Ensure `users` id type and related user columns are updated before creating
    # tables that reference `users.id` to avoid FK type mismatches.
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('metadata', sa.JSON(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'ESCALATED', name='conversation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_agent_status', 'conversations', ['assigned_agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_conversations_assigned_agent_id'), 'conversations', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_status', 'conversations', ['user_id', 'status'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_keyword'), 'routing_rules', ['keyword'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('escalation_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_policies_department_id'), 'sla_policies', ['department_id'], unique=False)
    op.create_index(op.f('ix_sla_policies_priority'), 'sla_policies', ['priority'], unique=False)
    op.create_index('ix_unique_sla_policy', 'sla_policies', ['department_id', 'priority'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'AGENT', 'BOT', 'SYSTEM', name='sender_type'), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sender', 'messages', ['conversation_id', 'sender_type'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    # ### Ensure `users` id type and related user columns are updated before creating
    # tables that reference `users.id` to avoid FK type mismatches. Move the user
    # alterations here (they were autogenerated later).
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('metadata', sa.JSON(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # Now safe to modify chat_logs and other tables that reference users
    op.add_column('chat_logs', sa.Column('ticket_id', sa.Integer(), nullable=False))
    op.alter_column('chat_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_chat_logs_ticket_id'), 'chat_logs', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    op.create_index('ix_chat_logs_user_ticket', 'chat_logs', ['user_id', 'ticket_id'], unique=False)
    op.drop_constraint(op.f('chat_logs_user_id_fkey'), 'chat_logs', type_='foreignkey')
    op.create_foreign_key(None, 'chat_logs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chunks', 'document_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('documents', sa.Column('owner_id', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('is_processed', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('documents', sa.Column('metadata', sa.JSON(), nullable=False))
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    op.drop_column('documents', 'is_confidential')
    op.drop_column('documents', 'source')
    op.alter_column('sentiment_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tickets', 'created_by_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tickets', 'assigned_agent_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticket_status'),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'),
               nullable=False)
    op.alter_column('tickets', 'sla_breached',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('tickets', 'escalation_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('tickets', 'reassigned_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_tickets_agent_status', 'tickets', ['assigned_agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_agent_id'), 'tickets', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_tickets_conversation_id'), 'tickets', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_tickets_created_by_id'), 'tickets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tickets_department_id'), 'tickets', ['department_id'], unique=False)
    op.create_index('ix_tickets_sla_due', 'tickets', ['sla_due_at'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_foreign_key(None, 'tickets', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'metadata')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_index('ix_tickets_sla_due', table_name='tickets')
    op.drop_index(op.f('ix_tickets_department_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_conversation_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_agent_id'), table_name='tickets')
    op.drop_index('ix_tickets_agent_status', table_name='tickets')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tickets', 'reassigned_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('tickets', 'escalation_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('tickets', 'sla_breached',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticket_status'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tickets', 'assigned_agent_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tickets', 'created_by_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sentiment_logs', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('documents', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('is_confidential', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'is_processed')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'owner_id')
    op.alter_column('chunks', 'document_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_logs', type_='foreignkey')
    op.drop_constraint(None, 'chat_logs', type_='foreignkey')
    op.create_foreign_key(op.f('chat_logs_user_id_fkey'), 'chat_logs', 'users', ['user_id'], ['id'])
    op.drop_index('ix_chat_logs_user_ticket', table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_ticket_id'), table_name='chat_logs')
    op.alter_column('chat_logs', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('chat_logs', 'ticket_id')
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_sender', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_unique_sla_policy', table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_priority'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_department_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_routing_rules_keyword'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index('ix_conversations_user_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_agent_id'), table_name='conversations')
    op.drop_index('ix_conversations_agent_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('departments')
    # ### end Alembic commands ###
