"""add user indexes

Revision ID: cada0755b062
Revises: fb5ae2bd1bbd
Create Date: 2026-02-20 12:14:43.146205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cada0755b062'
down_revision: Union[str, Sequence[str], None] = 'fb5ae2bd1bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_department', 'users', ['department'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_department', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
