"""sync_schema_2026

Revision ID: fb5ae2bd1bbd
Revises: a2e76fe5775c
Create Date: 2026-02-20 11:10:23.820933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5ae2bd1bbd'
down_revision: Union[str, Sequence[str], None] = 'a2e76fe5775c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
